AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  DeploymentBucket:
    Type: AWS::S3::Bucket
Outputs:
  DeploymentBucketName:
    Description: Deployment bucket name
    Value:
      Ref: DeploymentBucket



