AWSTemplateFormatVersion: "2010-09-09"
Description: Safya unified log stack
Metadata:
  Version: "0.1.0"
Parameters:
  AutoScalingEnabled:
    Type: String
    AllowedValues:
      - true
      - false
    Default: true
    Description: Enable auto scaling on this stack
  AutoScalingMaxCapacity:
    Type: Number
    Default: 200
    Description: If auto-scaling is enabled, the maximum capacity to scale dynamodb up to
  AutoScalingMinCapacity:
    Type: Number
    Default: 5
    Description: If auto-scaling is enabled, the minimum capacity to scale dynamodb down to
  InitialProvisionedCapacity:
    Type: Number
    Default: 5
    Description: The initial capacity to provision the dynamodb tables with
  PreferredPartitionCount:
    Type: Number
    Default: 10
    Description: Preferred number of partitions (this is only guaranteed in some circumstances).
Conditions:
  ProvisionAutoScaling:
    Fn::Equals:
      - Ref: AutoScalingEnabled
      - true
Resources:
  PartitionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: partitionId
          AttributeType: S
      KeySchema:
        - AttributeName: partitionId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits:
          Ref: InitialProvisionedCapacity
        WriteCapacityUnits:
          Ref: InitialProvisionedCapacity
  ConsumersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: consumerId
          AttributeType: S
        - AttributeName: partitionId
          AttributeType: S
      KeySchema:
        - AttributeName: partitionId
          KeyType: HASH
        - AttributeName: consumerId
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits:
          Ref: InitialProvisionedCapacity
        WriteCapacityUnits:
          Ref: InitialProvisionedCapacity
  PartitionsReadAutoScalingTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Condition: ProvisionAutoScaling
    Properties:
      MaxCapacity:
        Ref: AutoScalingMaxCapacity
      MinCapacity:
        Ref: AutoScalingMinCapacity
      ScalableDimension: dynamodb:table:ReadCapacityUnits
      RoleARN:
        Fn::GetAtt: [AutoScalingRole, Arn]
      ResourceId:
        Fn::Join:
          - /
          - - table
            - Ref: PartitionsTable
      ServiceNamespace: dynamodb
  PartitionsReadAutoScalingPolicy:
    Type: "AWS::ApplicationAutoScaling::ScalingPolicy"
    Condition: ProvisionAutoScaling
    Properties:
      PolicyName: PartitionsReadAutoScalingPolicy
      PolicyType: TargetTrackingScaling
      ScalingTargetId:
        Ref: PartitionsReadAutoScalingTarget
      TargetTrackingScalingPolicyConfiguration:
        TargetValue: 70.0
        ScaleInCooldown: 60
        ScaleOutCooldown: 60
        PredefinedMetricSpecification:
          PredefinedMetricType: DynamoDBReadCapacityUtilization
  PartitionsWriteAutoScalingTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Condition: ProvisionAutoScaling
    Properties:
      MaxCapacity:
        Ref: AutoScalingMaxCapacity
      MinCapacity:
        Ref: AutoScalingMinCapacity
      ScalableDimension: dynamodb:table:WriteCapacityUnits
      RoleARN:
        Fn::GetAtt: [AutoScalingRole, Arn]
      ResourceId:
        Fn::Join:
          - /
          - - table
            - Ref: PartitionsTable
      ServiceNamespace: dynamodb
  PartitionsWriteAutoScalingPolicy:
    Type: "AWS::ApplicationAutoScaling::ScalingPolicy"
    Condition: ProvisionAutoScaling
    Properties:
      PolicyName: PartitionsWriteAutoScalingPolicy
      PolicyType: TargetTrackingScaling
      ScalingTargetId:
        Ref: PartitionsWriteAutoScalingTarget
      TargetTrackingScalingPolicyConfiguration:
        TargetValue: 70.0
        ScaleInCooldown: 60
        ScaleOutCooldown: 60
        PredefinedMetricSpecification:
          PredefinedMetricType: DynamoDBWriteCapacityUtilization
  ConsumersReadAutoScalingTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Condition: ProvisionAutoScaling
    Properties:
      MaxCapacity:
        Ref: AutoScalingMaxCapacity
      MinCapacity:
        Ref: AutoScalingMinCapacity
      ScalableDimension: dynamodb:table:ReadCapacityUnits
      RoleARN:
        Fn::GetAtt: [AutoScalingRole, Arn]
      ResourceId:
        Fn::Join:
          - /
          - - table
            - Ref: ConsumersTable
      ServiceNamespace: dynamodb
  ConsumersReadAutoScalingPolicy:
    Type: "AWS::ApplicationAutoScaling::ScalingPolicy"
    Condition: ProvisionAutoScaling
    Properties:
      PolicyName: ConsumersReadAutoScalingPolicy
      PolicyType: TargetTrackingScaling
      ScalingTargetId:
        Ref: ConsumersReadAutoScalingTarget
      TargetTrackingScalingPolicyConfiguration:
        TargetValue: 70.0
        ScaleInCooldown: 60
        ScaleOutCooldown: 60
        PredefinedMetricSpecification:
          PredefinedMetricType: DynamoDBReadCapacityUtilization
  ConsumersWriteAutoScalingTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Condition: ProvisionAutoScaling
    Properties:
      MaxCapacity:
        Ref: AutoScalingMaxCapacity
      MinCapacity:
        Ref: AutoScalingMinCapacity
      ScalableDimension: dynamodb:table:WriteCapacityUnits
      RoleARN:
        Fn::GetAtt: [AutoScalingRole, Arn]
      ResourceId:
        Fn::Join:
          - /
          - - table
            - Ref: ConsumersTable
      ServiceNamespace: dynamodb
  ConsumersWriteAutoScalingPolicy:
    Type: "AWS::ApplicationAutoScaling::ScalingPolicy"
    Condition: ProvisionAutoScaling
    Properties:
      PolicyName: ConsumersWriteAutoScalingPolicy
      PolicyType: TargetTrackingScaling
      ScalingTargetId:
        Ref: ConsumersWriteAutoScalingTarget
      TargetTrackingScalingPolicyConfiguration:
        TargetValue: 70.0
        ScaleInCooldown: 60
        ScaleOutCooldown: 60
        PredefinedMetricSpecification:
          PredefinedMetricType: DynamoDBWriteCapacityUtilization
  AutoScalingRole:
    Type: AWS::IAM::Role
    Condition: ProvisionAutoScaling
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - application-autoscaling.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: PerformanceTestLambda
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:DescribeTable
                  - dynamodb:UpdateTable
                  - cloudwatch:PutMetricAlarm
                  - cloudwatch:DescribeAlarms
                  - cloudwatch:GetMetricStatistics
                  - cloudwatch:SetAlarmState
                  - cloudwatch:DeleteAlarms
                Resource: "*"
  EventsBucket:
    Type: AWS::S3::Bucket
Outputs:
  PartitionsTableName:
    Description: Partitions table name
    Value:
      Ref: PartitionsTable
  ConsumersTableName:
    Description: Consumers table name
    Value:
      Ref: ConsumersTable
  EventsBucketName:
    Description: Events bucket name
    Value:
      Ref: EventsBucket
  ConfigString:
    Description: "Safya configuration string. Use this for constructing a new Safya object: new Safya({ config: <SafyaConfig> })"
    Value:
      Fn::Sub: "{ \"partitionsTable\": \"${PartitionsTable}\", \"consumersTable\":\"${ConsumersTable}\", \"eventsBucket\":\"${EventsBucket}\", \"preferredPartitionCount\": ${PreferredPartitionCount} }"
